site_name: Projeto Back-end
theme:
  name: mkdocs
  palette:
    primary: blue
    accent: cyan
  font:
    text: Roboto
    code: Roboto Mono
  nav:
    - Home: index.md
    - Login: login.md
  user_color_mode_toggle: true